const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {resumableDownload}=require('../app/update-download.cjs');
test('download resumes after disconnect using backup and verifies SHA512',async()=>{
 const payload=Buffer.alloc(131072,17),sha512=crypto.createHash('sha512').update(payload).digest('base64');let ranges=[],hits=0;
 const server=http.createServer((req,res)=>{hits++;ranges.push(req.headers.range);const start=Number(/bytes=(\d+)/.exec(req.headers.range||'')?.[1]||0);if(hits===1){res.writeHead(200,{'content-length':payload.length});res.write(payload.subarray(0,32768));setTimeout(()=>res.destroy(),30);return;}res.writeHead(start?206:200,{'content-length':payload.length-start,...(start?{'content-range':`bytes ${start}-${payload.length-1}/${payload.length}`}:{})});res.end(payload.subarray(start));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'update-test-')),url=`http://127.0.0.1:${server.address().port}/`,dest=path.join(dir,'setup.exe');let messages=[];
 try{await resumableDownload(url,dest,{sha512},{request:(url,headers)=>http.request(url,{headers}),cacheDir:dir,fallback:url+'backup',say:x=>messages.push(x),delay:async()=>{}});assert.deepEqual(fs.readFileSync(dest),payload);assert.equal(ranges[1],'bytes=32768-');assert.ok(messages.length);assert.equal(fs.readdirSync(dir).filter(x=>x.endsWith('.part')).length,0);}finally{server.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('invalid hash cannot produce installer',async()=>{const server=http.createServer((req,res)=>res.end('corrupt'));await new Promise(r=>server.listen(0,'127.0.0.1',r));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'update-invalid-')),dest=path.join(dir,'setup.exe');try{await assert.rejects(resumableDownload(`http://127.0.0.1:${server.address().port}`,dest,{sha512:'bad'},{request:(url,headers)=>http.request(url,{headers}),cacheDir:dir,say:()=>{},delay:async()=>{}}),/校验失败/);assert.equal(fs.existsSync(dest),false);}finally{server.close();fs.rmSync(dir,{recursive:true,force:true});}});
