const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function collect(binary,args,onChunk,signal){return new Promise((resolve,reject)=>{let log='';const p=spawn(binary,args,{windowsHide:true,shell:false,signal,stdio:['ignore','pipe','pipe']});p.stderr.on('data',b=>log=(log+b).slice(-2000));p.stdout.on('data',b=>{try{onChunk(b);}catch(e){p.kill();reject(e);}});p.once('error',reject);p.once('close',code=>code===0?resolve():reject(Error(log||'分析终止')));});}
async function analyzeMedia(ffmpeg,ffprobe,input,signal,onUpdate=()=>{},cacheDir){
 let cache;try{const stat=fs.statSync(input);cache=cacheDir&&path.join(cacheDir,crypto.createHash('sha256').update(input+stat.size+stat.mtimeMs+'packets-v1').digest('hex')+'.json');if(cache&&fs.existsSync(cache))return JSON.parse(fs.readFileSync(cache,'utf8'));}catch{}
 const peaks=[],frames=[];let remain=Buffer.alloc(0),peak=0,count=0,line='';
 const wave=collect(ffmpeg,['-v','error','-nostdin','-i',input,'-map','0:a:0','-vn','-ac','1','-ar','2000','-c:a','pcm_f32le','-f','f32le','pipe:1'],b=>{const data=Buffer.concat([remain,b]);let i=0;for(;i+4<=data.length;i+=4){peak=Math.max(peak,Math.abs(data.readFloatLE(i)));if(++count===40){peaks.push(peak);peak=0;count=0;if(peaks.length>2000000)throw Error('音频过长');}}remain=data.subarray(i);},signal).then(()=>{if(count)peaks.push(peak);onUpdate({peaks,peakStep:.02});});
 function frameLine(s){const n=Number.parseFloat(s.split(',')[0]);if(Number.isFinite(n)&&n>=0)frames.push(n);if(frames.length>2000000)throw Error('帧数超过分析上限');}
 const timing=collect(ffprobe,['-v','error','-select_streams','v:0','-show_packets','-show_entries','packet=pts_time','-of','csv=p=0',input],b=>{line+=b.toString();const lines=line.split('\n');line=lines.pop();lines.forEach(frameLine);},signal).then(()=>{if(line)frameLine(line);frames.sort((a,b)=>a-b);for(let i=frames.length-1;i>0;i--)if(frames[i]===frames[i-1])frames.splice(i,1);onUpdate({frames});});
 const [a,f]=await Promise.allSettled([wave,timing]);const result={peaks:a.status==='fulfilled'?peaks:[],peakStep:.02,frames:f.status==='fulfilled'?frames:[],waveError:a.status==='rejected'?a.reason.message:'',frameError:f.status==='rejected'?f.reason.message:''};if(cache&&!signal?.aborted&&!result.frameError&&!result.waveError){fs.mkdirSync(cacheDir,{recursive:true});fs.writeFileSync(cache,JSON.stringify(result));}return result;
}
module.exports={analyzeMedia};
