const $=id=>document.getElementById(id),v=$('video'),notes=$('notes');
let cfg=structuredClone(defaults),url,source;
try{const saved=upgradeConfig(JSON.parse(localStorage.getItem('config')));if(validate(saved)){if(saved.seek===5)saved.seek=1;cfg=saved;}notes.value=localStorage.getItem('notes')||'';}catch{}
function say(s){$('message').textContent=s;}
function persist(){localStorage.setItem('notes',notes.value);}
notes.addEventListener('input',persist);
$('open').onclick=()=>$('file').click();
async function openVideo(f){if(!f)return;if($('export').disabled){say('请等待切割完成');return;}if(notes.value.trim()&&!confirm('打开新视频会重置右侧记录，是否继续？')){$('file').value='';return;}try{await window.desktop.setInput(f);}catch(e){say(e.message);return;}v.pause();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);v.src=url;v.playbackRate=1;source=sourceName(f.name);notes.value=initialNotes(source);persist();$('name').textContent=f.name;say('视频已打开');loadAnalysis();}
$('file').onchange=()=>openVideo($('file').files[0]);
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';document.body.classList.add('dragging');}});
document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});
document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');const files=Array.from(e.dataTransfer?.files||[]);const video=files.find(f=>f.type.startsWith('video/')||/\.(mp4|webm|mkv|mov|m4v|avi|mts|m2ts)$/i.test(f.name));if(video)openVideo(video);else say('请拖入一个视频文件');});

v.addEventListener('error',()=>say('无法播放该编码。请使用 H.264/AAC 的 MP4 或兼容的 WebM 文件。'));
v.addEventListener('timeupdate',()=>$('clock').textContent=format(v.currentTime));v.addEventListener('ratechange',()=>$('rate').textContent=v.playbackRate+'×');
function stamp(){if(!v.src||!Number.isFinite(v.duration)){say('请先打开可播放的视频');return;}try{if($('fine').checked&&!media.frames.length){say('帧时间轴尚未准备好，请等待分析完成');return;}const t=$('fine').checked?frameAt(media.frames,v.currentTime):v.currentTime;notes.value=appendBreakpoint(notes.value,source,t,$('fine').checked);notes.scrollTop=notes.scrollHeight;persist();say('已记录 '+breakpointTime(v.currentTime));}catch(e){say(e.message);}}
async function copy(){try{await window.desktop.copy(notes.value);say('已复制全部记录');}catch{say('复制失败，请手动选择文本复制');}}
$('stamp').onclick=stamp;$('copy').onclick=copy;
function act(k){if(k==='stamp')return stamp();if(k==='copy')return copy();if(!v.src)return;if(k==='toggle'){v.focus();if(v.paused)v.play().catch(e=>say(e.message));else v.pause();return;}if(k==='up'||k==='down'){v.muted=false;v.volume=Math.min(1,Math.max(0,v.volume+(k==='up'?1:-1)*cfg.volume/100));say('音量 '+Math.round(v.volume*100)+'%');}else if(k==='back'||k==='forward'){if($('fine').checked){if(!media.frames.length){say('帧时间轴尚未准备好');return;}v.pause();v.currentTime=frameAt(media.frames,v.currentTime,k==='forward'?1:-1);return;}if(Number.isFinite(v.duration))v.currentTime=Math.min(v.duration,Math.max(0,v.currentTime+(k==='forward'?1:-1)*cfg.seek));}else if(k.startsWith('speed'))v.playbackRate=cfg.speeds[Number(k.slice(-1))];}
let pendingToggleCode;
document.addEventListener('keydown',e=>{if($('dialog').open||$('importDialog').open)return;const key=chord(e),entry=Object.entries(cfg.keys).find(([,value])=>value===key);if(!entry)return;const typing=e.target.matches('textarea,input:not([type=range]),[contenteditable=true]');if(typing&&!['copy','stamp'].includes(entry[0]))return;e.preventDefault();e.stopImmediatePropagation();if(entry[0]==='toggle'){if(!e.repeat)pendingToggleCode=e.code;return;}if(e.repeat&&['copy','stamp','back','forward'].includes(entry[0]))return;act(entry[0]);},true);
document.addEventListener('keyup',e=>{if(!pendingToggleCode||e.code!==pendingToggleCode)return;pendingToggleCode=undefined;e.preventDefault();e.stopImmediatePropagation();if($('dialog').open||$('importDialog').open||e.target.matches('textarea,input:not([type=range]),[contenteditable=true]'))return;act('toggle');},true);
window.addEventListener('blur',()=>{pendingToggleCode=undefined;});
$('playToggle').onpointerdown=e=>{e.preventDefault();v.focus();};$('playToggle').onclick=()=>act('toggle');v.onclick=()=>act('toggle');
function syncControls(){$('playToggle').textContent=v.paused?'播放':'暂停';$('seekBar').max=Number.isFinite(v.duration)?v.duration:1;$('seekBar').value=v.currentTime;$('volumeBar').value=v.muted?0:v.volume;$('clock').textContent=format(v.currentTime);$('duration').textContent=format(Number.isFinite(v.duration)?v.duration:0);}
for(const event of ['play','pause','timeupdate','loadedmetadata','volumechange'])v.addEventListener(event,syncControls);
$('seekBar').oninput=()=>{if(Number.isFinite(v.duration)){v.currentTime=Number($('seekBar').value);showSeekHint(v.currentTime);}};$('volumeBar').oninput=()=>{v.muted=false;v.volume=Number($('volumeBar').value);};
for(const id of ['seekBar','volumeBar'])$(id).onpointerup=()=>v.focus();

const labels={toggle:'播放 / 暂停',stamp:'记录当前时间',copy:'复制全部记录',up:'增加音量',down:'降低音量',back:'快退',forward:'快进',speed0:'倍速档 1',speed1:'倍速档 2',speed2:'倍速档 3',speed3:'倍速档 4'};
function fill(s){$('fields').replaceChildren();for(const [k,title]of Object.entries(labels)){const row=document.createElement('label'),label=document.createElement('span'),input=document.createElement('input');label.textContent=title;input.value=s.keys[k];input.readOnly=true;input.dataset.key=k;input.setAttribute('aria-label',title+'快捷键');input.onkeydown=e=>{e.preventDefault();const c=chord(e);if(c)input.value=c;};row.append(label,input);if(k.startsWith('speed')){const rate=document.createElement('input');rate.type='number';rate.min='.25';rate.max='16';rate.step='.25';rate.value=s.speeds[Number(k.slice(-1))];rate.dataset.speed=k.slice(-1);rate.setAttribute('aria-label',title+'速度');row.append(rate);} $('fields').append(row);} $('seek').value=s.seek;$('volume').value=s.volume;$('configError').textContent='';}
$('settings').onclick=()=>{fill(cfg);$('dialog').showModal();};$('cancel').onclick=()=>$('dialog').close();$('reset').onclick=()=>fill(defaults);
$('config').onsubmit=async e=>{e.preventDefault();const s={keys:{},speeds:[],seek:Number($('seek').value),volume:Number($('volume').value)};document.querySelectorAll('[data-key]').forEach(i=>s.keys[i.dataset.key]=i.value);document.querySelectorAll('[data-speed]').forEach(i=>s.speeds[Number(i.dataset.speed)]=Number(i.value));if(!validate(s)){$('configError').textContent='快捷键不能重复；倍速须为 0.25—16，步长须在有效范围内。';return;}try{await window.desktop.saveConfig({config:s,audio:$('audio').checked});}catch(e){$('configError').textContent=e.message;return;}cfg=s;syncShortcutHelp();localStorage.setItem('config',JSON.stringify(cfg));$('dialog').close();say('设置已保存');};

const ready=window.desktop.loadConfig().then(async saved=>{const migrated=upgradeConfig(saved.config);if(validate(migrated)){cfg=migrated;await window.desktop.saveConfig({config:cfg});}else await window.desktop.saveConfig({config:cfg});$('audio').checked=saved.audio!==false;$('fine').checked=saved.fine===true;syncShortcutHelp();nameList=Array.isArray(saved.nameList)?saved.nameList:[];renderNameList();}).catch(e=>say('配置读取失败：'+e.message));
$('settings').disabled=true;ready.finally(()=>$('settings').disabled=false);
$('audio').onchange=async()=>{try{await window.desktop.saveConfig({audio:$('audio').checked});}catch(e){say('设置保存失败：'+e.message);}};
window.desktop.onProgress(say);
$('export').onclick=async()=>{await ready;const controls=[$('export'),$('open'),$('audio')];controls.forEach(x=>x.disabled=true);try{notes.value=normalizeNotes(notes.value);persist();await window.desktop.saveConfig({audio:$('audio').checked});const result=await window.desktop.exportSegments(notes.value);say(result.canceled?'已取消导出':`已导出 ${result.count} 段视频、${result.audioCount} 段音频。目录：${result.folder}`+(result.noAudio?'（原视频无音轨）':''));}catch(e){say(e.message);}finally{controls.forEach(x=>x.disabled=false);}};

let nameList=[];
function renderNameList(){$('nameList').replaceChildren();if(!nameList.length){const hint=document.createElement('small');hint.textContent='导入名称后，会在这里显示可点击的按钮。';$('nameList').append(hint);}for(const name of nameList){const b=document.createElement('button');b.type='button';b.textContent=name;b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{const caret=notes.selectionStart;notes.setRangeText(name,caret,caret,'end');persist();notes.focus();say('已粘贴名称');};$('nameList').append(b);}}
$('import').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('importCancel').onclick=()=>$('importDialog').close();$('delimiter').onchange=()=>{$('customRow').hidden=$('delimiter').value!=='custom';};$('namesFile').onchange=async()=>{const file=$('namesFile').files[0];if(!file)return;if(file.size>200000){$('importError').textContent='文件过大（最多 200KB）';return;}$('importText').value=await file.text();};
$('importForm').onsubmit=async e=>{e.preventDefault();try{const list=importNames($('importText').value,$('delimiter').value,$('customDelimiter').value);await window.desktop.saveConfig({nameList:list});nameList=list;renderNameList();$('importDialog').close();say('已导入 '+list.length+' 个可选名称');}catch(e){$('importError').textContent=e.message;}};

let media={peaks:[],frames:[],peakStep:.02},zoomSpan=0,analysisToken=0;
const canvas=$('wave'),ctx=canvas.getContext('2d');
function waveRange(){const duration=Number.isFinite(v.duration)?v.duration:1,span=zoomSpan?Math.min(duration,zoomSpan):duration;const start=Math.max(0,Math.min(duration-span,v.currentTime-span/2));return {start,span,duration};}
function drawWave(){const width=Math.max(1,canvas.clientWidth),height=canvas.clientHeight,ratio=window.devicePixelRatio||1;canvas.width=width*ratio;canvas.height=height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);const {start,span}=waveRange();ctx.strokeStyle='#61b9dc';ctx.beginPath();for(let x=0;x<width;x++){const a=Math.floor((start+x/width*span)/media.peakStep),b=Math.max(a+1,Math.ceil((start+(x+1)/width*span)/media.peakStep));let peak=0;for(let i=a;i<b&&i<media.peaks.length;i++)peak=Math.max(peak,media.peaks[i]||0);const h=Math.min(1,peak)*height*.38;ctx.moveTo(x,height/2-h);ctx.lineTo(x,height/2+h);}ctx.stroke();const points=/^breakpoints:(.*)$/m.exec(notes.value)?.[1].split(',')||[];ctx.strokeStyle='#667c9e';for(const point of points){const a=/^(\d+):([0-5]\d)(?:\.(\d{3}))?$/.exec(point);if(!a)continue;const t=Number(a[1])*60+Number(a[2])+Number(a[3]||0)/1000;if(t<start||t>start+span)continue;const x=(t-start)/span*width;ctx.beginPath();ctx.moveTo(x,16);ctx.lineTo(x,height);ctx.stroke();}const caret=(v.currentTime-start)/span*width;ctx.strokeStyle='#ffcf91';ctx.beginPath();ctx.moveTo(caret,0);ctx.lineTo(caret,height);ctx.stroke();ctx.fillStyle='#99a9c0';ctx.font='11px sans-serif';ctx.fillText(breakpointTime(start,true),5,14);ctx.fillText(breakpointTime(start+span,true),Math.max(5,width-85),14);$('zoomInfo').textContent=`显示 ${span.toFixed(3)} 秒 · 滚轮上放大，下缩小 · 点击定位`;}
async function loadAnalysis(){const token=++analysisToken;media={peaks:[],frames:[],peakStep:.02};zoomSpan=0;$('waveStatus').textContent='正在分析音频和帧时间轴…';if($('fine').checked){notes.value=precisionNotes(notes.value,source);persist();}drawWave();try{const result=await window.desktop.analyze();if(token!==analysisToken)return;media=result;$('waveStatus').textContent=`${media.peaks.length?'音量波形就绪':'无音轨或波形不可用'} · ${media.frames.length?'逐帧就绪':'帧分析失败'}`;drawWave();}catch(e){if(token===analysisToken)$('waveStatus').textContent='分析失败：'+e.message;}}
$('fine').onchange=async()=>{if($('fine').checked){v.pause();if(source){notes.value=precisionNotes(notes.value,source);persist();}}try{await window.desktop.saveConfig({fine:$('fine').checked});}catch(e){say(e.message);}drawWave();};
canvas.addEventListener('wheel',e=>{e.preventDefault();const {span,duration}=waveRange();zoomSpan=Math.max(.05,Math.min(duration,span*(e.deltaY<0?.75:1/.75)));drawWave();},{passive:false});
canvas.onclick=e=>{if(!Number.isFinite(v.duration))return;const {start,span}=waveRange();let t=start+(e.clientX-canvas.getBoundingClientRect().left)/canvas.clientWidth*span;if($('fine').checked){if(!media.frames.length)return;t=frameAt(media.frames,t);}v.pause();v.currentTime=t;drawWave();};
v.addEventListener('timeupdate',drawWave);v.addEventListener('loadedmetadata',drawWave);notes.addEventListener('input',drawWave);new ResizeObserver(drawWave).observe(canvas);

window.desktop.onUpdateState(say);
window.desktop.onMediaUpdate(part=>{media={...media,...part};$('waveStatus').textContent=`${media.peaks.length?'音量波形就绪':'正在分析音量波形…'} · ${media.frames.length?'逐帧就绪':'正在读取帧时间…'}`;drawWave();});
// Checkboxes toggle with the mouse without stealing focus, including label clicks.
let checkboxFocus;
document.querySelectorAll('input[type=checkbox]').forEach(el=>el.tabIndex=-1);
document.addEventListener('pointerdown',e=>{const label=e.target.closest('label');const box=e.target.matches('input[type=checkbox]')?e.target:label?.querySelector('input[type=checkbox]');if(box){checkboxFocus=document.activeElement;e.preventDefault();}},true);
document.addEventListener('click',e=>{const label=e.target.closest('label'),box=label?.querySelector('input[type=checkbox]');if(box&&e.target!==box){e.preventDefault();box.click();return;}if(e.target.matches('input[type=checkbox]')&&checkboxFocus){const previous=checkboxFocus;checkboxFocus=null;queueMicrotask(()=>previous?.focus({preventScroll:true}));}},true);

function syncShortcutHelp(){const k=cfg.keys;const display=x=>x==='Space'?'空格':x;$('shortcutHelp').textContent=`松开 ${display(k.toggle)} 播放 / 暂停 · ${display(k.back)} / ${display(k.forward)} 快退 / 快进 · ${display(k.up)} / ${display(k.down)} 音量 · ${[0,1,2,3].map(i=>display(k['speed'+i])).join(' / ')} 倍速 · ${display(k.stamp)} 记录 · ${display(k.copy)} 复制`;$('notesShortcuts').textContent=`记录时间：${display(k.stamp)} · 复制内容：${display(k.copy)}`;}
syncShortcutHelp();
function showSeekHint(time,clientX){const bar=$('seekBar'),hint=$('seekHint'),rect=bar.getBoundingClientRect();const ratio=Number.isFinite(v.duration)&&v.duration>0?time/v.duration:0;const x=clientX===undefined?ratio*rect.width:clientX-rect.left;hint.textContent=format(time);hint.hidden=false;hint.style.left=Math.max(50,Math.min(rect.width-50,x))+'px';}
$('seekBar').addEventListener('pointermove',e=>{if(Number.isFinite(v.duration)){const rect=$('seekBar').getBoundingClientRect();const ratio=Math.max(0,Math.min(1,(e.clientX-rect.left-8)/Math.max(1,rect.width-16)));showSeekHint(ratio*v.duration,e.clientX);}});
$('seekBar').addEventListener('pointerleave',()=>{$('seekHint').hidden=true;});
$('seekBar').addEventListener('blur',()=>{$('seekHint').hidden=true;});
$('fullscreen').onpointerdown=e=>e.preventDefault();
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('videoStage').requestFullscreen();v.focus();}catch(e){say('全屏失败：'+e.message);}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏';$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'退出全屏':'全屏播放');v.focus();});
