const $=id=>document.getElementById(id),v=$('video'),notes=$('notes');
let cfg=structuredClone(defaults),url,source;
try{const saved=upgradeConfig(JSON.parse(localStorage.getItem('config')));if(validate(saved))cfg=saved;notes.value=localStorage.getItem('notes')||'';}catch{}
function say(s){$('message').textContent=s;}
function persist(){localStorage.setItem('notes',notes.value);refreshTargets();}
notes.addEventListener('input',persist);
$('open').onclick=()=>$('file').click();
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(notes.value.trim()&&!confirm('打开新视频会重置右侧记录，是否继续？')){$('file').value='';return;}try{await window.desktop.setInput(f);}catch(e){say(e.message);return;}v.pause();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);v.src=url;v.playbackRate=1;source=sourceName(f.name);notes.value=initialNotes(source);persist();$('name').textContent=f.name;say('视频已打开');};
v.addEventListener('error',()=>say('无法播放该编码。请使用 H.264/AAC 的 MP4 或兼容的 WebM 文件。'));
v.addEventListener('timeupdate',()=>$('clock').textContent=format(v.currentTime));v.addEventListener('ratechange',()=>$('rate').textContent=v.playbackRate+'×');
function stamp(){if(!v.src||!Number.isFinite(v.duration)){say('请先打开可播放的视频');return;}try{notes.value=appendBreakpoint(notes.value,source,v.currentTime);notes.scrollTop=notes.scrollHeight;persist();say('已记录 '+breakpointTime(v.currentTime));}catch(e){say(e.message);}}
async function copy(){try{await window.desktop.copy(notes.value);say('已复制全部记录');}catch{say('复制失败，请手动选择文本复制');}}
$('stamp').onclick=stamp;$('copy').onclick=copy;
function act(k){if(k==='stamp')return stamp();if(k==='copy')return copy();if(!v.src)return;if(k==='toggle'){if(v.paused)v.play().catch(e=>say(e.message));else v.pause();return;}if(k==='up'||k==='down'){v.muted=false;v.volume=Math.min(1,Math.max(0,v.volume+(k==='up'?1:-1)*cfg.volume/100));say('音量 '+Math.round(v.volume*100)+'%');}else if(k==='back'||k==='forward'){if(Number.isFinite(v.duration))v.currentTime=Math.min(v.duration,Math.max(0,v.currentTime+(k==='forward'?1:-1)*cfg.seek));}else if(k.startsWith('speed'))v.playbackRate=cfg.speeds[Number(k.slice(-1))];}
document.addEventListener('keydown',e=>{if($('dialog').open||$('importDialog').open)return;const key=chord(e),entry=Object.entries(cfg.keys).find(([,value])=>value===key);if(!entry)return;const typing=e.target.matches('textarea,input,[contenteditable=true]');if(typing&&!['copy','stamp'].includes(entry[0]))return;e.preventDefault();if(e.repeat&&['copy','stamp','toggle'].includes(entry[0]))return;act(entry[0]);});
const labels={toggle:'播放 / 暂停',stamp:'记录当前时间',copy:'复制全部记录',up:'增加音量',down:'降低音量',back:'快退',forward:'快进',speed0:'倍速档 1',speed1:'倍速档 2',speed2:'倍速档 3',speed3:'倍速档 4'};
function fill(s){$('fields').replaceChildren();for(const [k,title]of Object.entries(labels)){const row=document.createElement('label'),label=document.createElement('span'),input=document.createElement('input');label.textContent=title;input.value=s.keys[k];input.readOnly=true;input.dataset.key=k;input.setAttribute('aria-label',title+'快捷键');input.onkeydown=e=>{e.preventDefault();const c=chord(e);if(c)input.value=c;};row.append(label,input);if(k.startsWith('speed')){const rate=document.createElement('input');rate.type='number';rate.min='.25';rate.max='16';rate.step='.25';rate.value=s.speeds[Number(k.slice(-1))];rate.dataset.speed=k.slice(-1);rate.setAttribute('aria-label',title+'速度');row.append(rate);} $('fields').append(row);} $('seek').value=s.seek;$('volume').value=s.volume;$('configError').textContent='';}
$('settings').onclick=()=>{fill(cfg);$('dialog').showModal();};$('cancel').onclick=()=>$('dialog').close();$('reset').onclick=()=>fill(defaults);
$('config').onsubmit=async e=>{e.preventDefault();const s={keys:{},speeds:[],seek:Number($('seek').value),volume:Number($('volume').value)};document.querySelectorAll('[data-key]').forEach(i=>s.keys[i.dataset.key]=i.value);document.querySelectorAll('[data-speed]').forEach(i=>s.speeds[Number(i.dataset.speed)]=Number(i.value));if(!validate(s)){$('configError').textContent='快捷键不能重复；倍速须为 0.25—16，步长须在有效范围内。';return;}try{await window.desktop.saveConfig({config:s,audio:$('audio').checked});}catch(e){$('configError').textContent=e.message;return;}cfg=s;localStorage.setItem('config',JSON.stringify(cfg));$('dialog').close();say('设置已保存');};

const ready=window.desktop.loadConfig().then(async saved=>{const migrated=upgradeConfig(saved.config);if(validate(migrated)){cfg=migrated;await window.desktop.saveConfig({config:cfg});}else await window.desktop.saveConfig({config:cfg});$('audio').checked=saved.audio!==false;nameList=Array.isArray(saved.nameList)?saved.nameList:[];renderNameList();refreshTargets();}).catch(e=>say('配置读取失败：'+e.message));
$('settings').disabled=true;ready.finally(()=>$('settings').disabled=false);
$('audio').onchange=async()=>{try{await window.desktop.saveConfig({audio:$('audio').checked});}catch(e){say('设置保存失败：'+e.message);}};
window.desktop.onProgress(say);
$('export').onclick=async()=>{await ready;const controls=[$('export'),$('open'),$('audio')];controls.forEach(x=>x.disabled=true);try{await window.desktop.saveConfig({audio:$('audio').checked});const result=await window.desktop.exportSegments(notes.value);say(result.canceled?'已取消导出':`已导出 ${result.count} 段视频、${result.audioCount} 段音频。目录：${result.folder}`+(result.noAudio?'（原视频无音轨）':''));}catch(e){say(e.message);}finally{controls.forEach(x=>x.disabled=false);}};

let nameList=[];
function refreshTargets(){const old=Number($('nameTarget').value);const m=/^names:(.*)$/m.exec(notes.value);$('nameTarget').replaceChildren();if(!m)return;const names=m[1].split(',');names.forEach((name,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+' · '+name;$('nameTarget').append(o);});$('nameTarget').value=Math.min(Number.isFinite(old)?old:0,names.length-1);}
function selectCursorName(){const start=notes.value.indexOf('\nnames:');if(start<0)return;const position=notes.selectionStart-(start+7);if(position<0)return;const index=notes.value.slice(start+7,start+7+position).split(',').length-1;$('nameTarget').value=index;}
notes.addEventListener('click',selectCursorName);notes.addEventListener('keyup',selectCursorName);notes.addEventListener('select',selectCursorName);
function renderNameList(){$('nameList').replaceChildren();if(!nameList.length){const hint=document.createElement('small');hint.textContent='导入名称后，会在这里显示可点击的按钮。';$('nameList').append(hint);}for(const name of nameList){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=()=>{try{const index=Number($('nameTarget').value);notes.value=replaceName(notes.value,index,name);persist();$('nameTarget').value=index;say('已修改片段 '+(index+1)+' 的名称');}catch(e){say(e.message);}};$('nameList').append(b);}}
$('import').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('importCancel').onclick=()=>$('importDialog').close();$('delimiter').onchange=()=>{$('customRow').hidden=$('delimiter').value!=='custom';};$('namesFile').onchange=async()=>{const file=$('namesFile').files[0];if(!file)return;if(file.size>200000){$('importError').textContent='文件过大（最多 200KB）';return;}$('importText').value=await file.text();};
$('importForm').onsubmit=async e=>{e.preventDefault();try{const list=importNames($('importText').value,$('delimiter').value,$('customDelimiter').value);await window.desktop.saveConfig({nameList:list});nameList=list;renderNameList();$('importDialog').close();say('已导入 '+list.length+' 个可选名称');}catch(e){$('importError').textContent=e.message;}};
